services:
  - type: web
    name: lme-price-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: basic
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PORT
        value: 10000
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true 